# Github Actions file which runs on tagged releases, and calls
# a reusable workflow file in python-build.yml (same directory)

name: Release python package

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow on any tag push.
  workflow_dispatch:

jobs:
  release:
    uses: WemoveEU/ci-workflows/.github/workflows/python-build.yml@v2
